spring.application.name=ClinicaPopular

#Porta do Servidor
server.port=8080

#Conex�o com o DB
spring.datasource.url=jdbc:postgresql://localhost:5432/ClinicaPopularAPI
spring.datasource.username=postgres
spring.datasource.password=pn010400

#DDL - Como  o hibernate trata a estrutura do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect